import * as SQLite from 'expo-sqlite';

const db = SQLite.openDatabaseSync('alkasense.db');

export async function initDatabase(): Promise<void> {
  await db.execAsync(`
    PRAGMA journal_mode = WAL;
    PRAGMA foreign_keys = ON;
  `);
  await createTables();
}

async function createTables(): Promise<void> {
  await db.execAsync(`
    CREATE TYPE user_role AS ENUM ('Researcher', 'Field Evaluator', 'Lab Technician', 'Administrator');
    CREATE TYPE gt_classes AS ENUM('Null', 'Low GT', 'Intermediate GT', 'High GT');


    -- Users table
    CREATE TABLE IF NOT EXISTS users (
      id            TEXT PRIMARY KEY,     -- Firebase UID

      name          TEXT NOT NULL,
      email         TEXT NOT NULL UNIQUE,
      role          user_role NOT NULL,
      institution   TEXT NOT NULL DEFAULT 'Philippine Rice Research Institute',
  
      created_at    DATETIME NOT NULL DEFAULT (datetime('now')),
      is_deleted    BOOLEAN NOT NULL DEFAULT FALSE
    );

    -- Sessions table
    CREATE TABLE IF NOT EXISTS sessions (
      id                TEXT PRIMARY KEY,       -- UUID generated by expo-crypto

      evaluator_id      TEXT NOT NULL REFERENCES users(id),

      name              TEXT NOT NULL UNIQUE,
      batch_identifier  TEXT NOT NULL UNIQUE,
      evaluation_date   DATETIME NOT NULL DEFAULT (datetime('now')),
      completion_date   DATETIME,

      koh_concentration   REAL NOT NULL,
      incubation_duration REAL NOT NULL,
      incubation_temp     REAL NOT NULL,

      status  TEXT NOT NULL DEFAULT 'Active'
        CHECK (status IN (
          'Active',
          'Completed'
        )),
    );

    -- Samples table
    CREATE TABLE IF NOT EXISTS samples (
      id                TEXT PRIMARY KEY,     -- UUID generated by expo-crypto

      session_id        TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,

      sample_identifier TEXT NOT NULL UNIQUE,
      grain_count       INT NOT NULL,

      gt_class          gt_classes NOT NULL DEFAULT 'Null',
      asv_score         INT NOT NULL DEFAULT 0
        CHECK (asv_score BETWEEN 0 AND 7)

      rice_variety      TEXT NOT NULL
        CHECK (rice_variety IN (
          'NSIC Rc 222',
          'NSIC Rc 160',
          'PSB Rc 18',
          'PSB Rc 82',
          'IR64',
          'IR72'
        )),

      status  TEXT NOT NULL DEFAULT 'Pending'
        CHECK (status IN (
          'Confirmed',
          'Image Submitted',
          'Pending'
        )),
    
      created_at        DATETIME NOT NULL DEFAULT (datetime('now'))
    );

    -- Grain images table
    CREATE TABLE IF NOT EXISTS grain_images (
      id              TEXT PRIMARY KEY,         -- UUID generated by expo-crypto

      sample_id       TEXT NOT NULL REFERENCES samples(id),
      file_path       TEXT NOT NULL UNIQUE,

      validation_status TEXT NOT NULL
        CHECK (validation_status IN (
          'Protocol Violation',
          'Quality Failure',
          'Accepted'
      ))
    );

    -- Rejection log table
    CREATE TABLE IF NOT EXISTS rejection_log (
      id              TEXT PRIMARY KEY,         -- UUID generated by expo-crypto

      grain_image_id  TEXT NOT NULL UNIQUE REFERENCES grain_images(id) ON DELETE CASCADE,
      evaluator_id    TEXT NOT NULL REFERENCES sessions(evaluator_id),

      rejection_layer TEXT NOT NULL
        CHECK (rejection_layer IN (
          'Protocol',
          'Quality'
      ))

      checklist_uv_light      BOOLEAN NOT NULL DEFAULT FALSE,
      checklist_white_tray    BOOLEAN NOT NULL DEFAULT FALSE,
      checklist_single_layer  BOOLEAN NOT NULL DEFAULT FALSE,
      checklist_frame_aligned BOOLEAN NOT NULL DEFAULT FALSE,

      failed_condition  TEXT NOT NULL,
      rejection_reason  TEXT NOT NULL,

      validation_timestamp    REAL NOT NULL,
      logged_at               DATETIME NOT NULL DEFAULT (datetime('now'))
    );

    -- Evaluation records table (created after expert observation is submitted)
    CREATE TABLE IF NOT EXISTS evaluation_records (
      id              TEXT PRIMARY KEY,         -- UUID generated by expo-crypto

      sample_id       TEXT NOT NULL REFERENCES samples(id),
      grain_image_id  TEXT NOT NULL REFERENCES grain_images(id),
      evaluator_id    TEXT NOT NULL REFERENCES users(id),

      evaluation_notes  TEXT,

      status          TEXT NOT NULL DEFAULT 'For Evaluation'
        CHECK (status IN (
          'For Evaluation',
          'Draft Generated',
          'Confirmed'
        )),

      created_at      DATETIME NOT NULL DEFAULT (datetime('now')),
      evaluated_at    DATETIME
    );

    -- Observation Profiles table
    CREATE TABLE IF NOT EXISTS observation_profiles (
      id              TEXT PRIMARY KEY,       -- UUID generated by expo-crypto

      eval_record_id  TEXT UNIQUE NOT NULL REFERENCES evaluation_records(id) ON DELETE CASCADE,

      spreading_pattern TEXT NOT NULL
        CHECK (spreading_pattern IN (
          'Smooth and Continuous',
          'Ragged and Fragmented',
          'Partial Spreading Only',
          'No Spreading'
        )),

      grain_translucency TEXT NOT NULL
        CHECK (grain_translucency IN (
          'Fully Translucent',
          'Partially Translucent',
          'Opaque'
        )),

      score_uniformity TEXT NOT NULL
        CHECK (score_uniformity IN (
          'Uniform',
          'Moderate Variation',
          'High Variation'
        )),

      anomaly_flags TEXT[] NOT NULL
        CHECK (
          anomaly_flags <@ ARRAY[
            'Longitudinal Cracking',
            'Unilateral Spreading',
            'Floating Grains',
            'No Anomaly'
          ]
          AND (
            anomaly_flags = ARRAY['No Anomaly']
            OR NOT ('No Anomaly' = ANY(anomaly_flags))
          )
        ),

      koh_appearance TEXT NOT NULL
        CHECK (koh_appearance IN (
          'Clear',
          'Mildly Clouded',
          'Heavily Clouded'
        ))
    );

    -- Draft scores table (AI-generated)
    CREATE TABLE IF NOT EXISTS draft_scores (
      id              TEXT PRIMARY KEY,         -- UUID generated by expo-crypto

      eval_record_id       TEXT UNIQUE NOT NULL REFERENCES evaluation_records(id) ON DELETE CASCADE,

      predicted_asv_score   INT NOT NULL,
        CHECK (predicted_asv_score BETWEEN 1 AND 7)

      predicted_gt_class    gt_classes NOT NULL DEFAULT 'Null',
      raw_confidence        REAL NOT NULL,
      calibrated_certainty  REAL NOT NULL,
      overlay_file_path     TEXT UNIQUE,

      remark_conflict_resolution  TEXT,
      remark_score_deviation      TEXT
    );

    -- Reference case table (only created during FR-M3-34)
    CREATE TABLE IF NOT EXISTS reference_cases (
      id              TEXT PRIMARY KEY,         -- UUID generated by expo-crypto

      evaluator_id    TEXT NOT NULL REFERENCES evaluation_records(evaluator_id),
      session_id      TEXT NOT NULL REFERENCES sessions(id),
      sample_id       TEXT NOT NULL REFERENCES evaluation_records(sample_id),
      grain_image_id  TEXT NOT NULL REFERENCES evaluation_records(grain_image_id),

      eval_record_id  TEXT NOT NULL UNIQUE REFERENCES evaluation_records(id),
      observation_profile_id  TEXT NOT NULL REFERENCES observation_profiles(id),
      draft_score_id  TEXT NOT NULL REFERENCES draft_scores(id)
    );

    -- Session report table (created upon session creation, always being regenerated after a sample is registered)
    CREATE TABLE IF NOT EXISTS session_report (
      id              TEXT PRIMARY KEY,         -- UUID generated by expo-crypto

     
    );

  

    -- Audit log table
    CREATE TABLE IF NOT EXISTS audit_log (
      id              TEXT PRIMARY KEY,         -- UUID generated by expo-crypto

      user_id         TEXT NOT NULL REFERENCES users(id),
      action          TEXT NOT NULL,
      entity          TEXT NOT NULL,

      created_at      DATETIME NOT NULL DEFAULT (datetime('now'))
    );

}

export default db;